spring:
  application:
    name: feign
#feign声明客户端
#集成ribbon和hystrix
#声明客户端
#ribbon的负载均衡和重试
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  
item-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

#hystrix降级和熔断   
feign:
  hystrix:
    enabled: true    
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500    
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream   
    
    