spring:
  application:
    name: config-server
  profiles:
    active: native 
    
#默认可以不配置     
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/liwei009/sp-config
#          searchPaths: config
          #username: your-username
          #password: your-password  
  rabbitmq:
    host: 192.168.179.128
    port: 5672
    username: admin
    password: admin   

  sleuth:
    sampler:
      probability: 0.1    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh      
      
      
      
      
      